capelco/urls.py
from django.contrib import admin
from django.urls import path, include
from accounts.views import AccountLoginView

urlpatterns = [
    path('xhDmaaly/', admin.site.urls),
    path('', AccountLoginView.as_view(), name='home_login_view'),
    path('account/', include('accounts.urls')),
    path('dashboard/', include('turn_on.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('location/', include('locations.urls')),
]

dashboard/urls.py
from django.urls import path

from dashboard.modules.views import dashboard_home as home_view
from dashboard.modules.views import dashboard_users as user_view

urlpatterns = [
    # Dashboard
    path('', home_view.DashboardHomeView.as_view(), name='dashboard_home_view'),

    # Add
    path('', home_view.DashboardHomeView.as_view(), name='dashboard_home_view'),

    # Users
    path('users/', user_view.DashboardUserView.as_view(), name='dashboard_user_view'),

]

turn_on/urls.py
from django.urls import path

from turn_on.modules.views import membership_view as membership
from turn_on.modules.views import turn_on_view as turn_on

urlpatterns = [
    # Membership
    path('membership/list', membership.MembershipListView.as_view(), name='membership_list'),
    path('membership/create', membership.MembershipCreateView.as_view(), name='membership_create'),
    path('membership/<pk>/update', membership.MembershipUpdateView.as_view(), name='membership_update'),
    path('membership/<pk>/delete', membership.MembershipDeleteView.as_view(), name='membership_delete'),
    path('membership/<pk>/detail', membership.MembershipDetailView.as_view(), name='membership_detail'),

    # TurnOn
    path('turn-on/list', turn_on.TurnOnListView.as_view(), name='turn_on_list'),
    path('turn-on/create', turn_on.TurnOnCreateView.as_view(), name='turn_on_create'),
    path('turn-on/<pk>/update', turn_on.TurnOnUpdateView.as_view(), name='turn_on_update'),
    path('turn-on/<pk>/delete', turn_on.TurnOnDeleteView.as_view(), name='turn_on_delete'),
    path('turn-on/<pk>/detail', turn_on.TurnOnDetailView.as_view(), name='turn_on_detail'),
]

dashboard/models.py
from django.db import models

# Create your models here.

turn_on/models.py
from django.db import models
from django_extensions.db import fields as extension_fields

# Create your models here.
from turn_on.constants import CONNECTION_TYPE_CHOICES, INSTALLATION_TYPE_CHOICES


class Membership(models.Model):
    name = models.CharField(max_length=64, blank=False, null=False)
    slug = extension_fields.AutoSlugField(populate_from='name', blank=True, null=True)
    active = models.BooleanField(default=True)

    created = models.DateTimeField(null=False, auto_now_add=True)
    updated = models.DateTimeField(null=False, auto_now=True)
    created_by = models.ForeignKey('accounts.Account', on_delete=models.SET_NULL, null=True, db_index=False,
                                   related_name='created_membership', blank=True)
    last_updated_by = models.ForeignKey('accounts.Account', on_delete=models.SET_NULL, null=True, db_index=False,
                                        related_name='updated_membership', blank=True)

    class Meta:
        ordering = ('name',)

    def __str__(self):
        return self.name


class TurnOn(models.Model):
    number = models.CharField(max_length=16, blank=True, null=True)
    first_name = models.CharField(max_length=24, blank=False, null=False)
    middle_name = models.CharField(max_length=24, blank=True, null=True)
    last_name = models.CharField(max_length=24, blank=False, null=False)
    spouse = models.CharField(max_length=64, blank=True, null=True)
    address = models.CharField(max_length=254, blank=True, null=True)
    cons = models.CharField(max_length=16, blank=True, null=True)
    install = models.CharField(max_length=64, choices=INSTALLATION_TYPE_CHOICES, blank=True, null=True, default='')
    connection = models.CharField(max_length=64, choices=CONNECTION_TYPE_CHOICES, default='')
    amount = models.DecimalField(max_digits=24, decimal_places=2, blank=True, null=True)
    or_number = models.CharField(max_length=64, blank=True, null=True)
    distance = models.IntegerField(blank=False, null=False)
    feeder = models.CharField(max_length=12, blank=False, null=False)
    year = models.IntegerField(blank=False, null=False)

    area = models.ForeignKey('locations.City', related_name='area_turn_on', null=True, on_delete=models.SET_NULL)
    municipality = models.ForeignKey('locations.City', related_name='municipality_turn_on', null=True,
                                     on_delete=models.SET_NULL)
    barangay = models.ForeignKey('locations.Barangay', related_name='barangay_turn_on', null=True,
                                 on_delete=models.SET_NULL)

    is_approved = models.BooleanField(default=False)

    created = models.DateTimeField(null=False, auto_now_add=True)
    updated = models.DateTimeField(null=False, auto_now=True)

    or_created = models.ForeignKey('datesdim.DateDim', related_name='or_date', on_delete=models.SET_NULL, null=True,
                                   blank=True)
    approved_date = models.ForeignKey('datesdim.DateDim', related_name='date_approved', on_delete=models.SET_NULL,
                                      null=True, blank=True)
    membership = models.ForeignKey(Membership, related_name='membership_type', on_delete=models.SET_NULL, null=True,
                                   blank=True)

    created_by = models.ForeignKey('accounts.Account', on_delete=models.SET_NULL, null=True, db_index=False,
                                   related_name='created_turn_on', blank=True)
    last_updated_by = models.ForeignKey('accounts.Account', on_delete=models.SET_NULL, null=True, db_index=False,
                                        related_name='updated_turn_on', blank=True)

    class Meta:
        ordering = ('number',)

    def __str__(self):
        return f'{self.first_name} {self.last_name}'

    def get_full_name(self):
        if self.first_name != '' and self.last_name != '' and self.middle_name != '':
            return '{}, {} {}.'.format(
                self.last_name, self.first_name, self.middle_name[0]
            )
        elif self.first_name != '' and self.last_name != '':
            return '{}, {}'.format(
                self.last_name, self.first_name
            )
        else:
            try:
                if self.account.username is not None:
                    return self.account.username
            except AttributeError:
                return 'Unnamed'
            return 'Unnamed'

turn_on/forms.py
from django import forms

from turn_on.models import Membership, TurnOn


class MembershipForm(forms.ModelForm):
    class Meta:
        model = Membership
        fields = ('name', 'active')


class TurnOnForm(forms.ModelForm):
    class Meta:
        model = TurnOn
        fields = (
            'number',
            'first_name',
            'middle_name',
            'last_name',
            'spouse',
            'address',
            'cons',
            'install',
            'connection',
            'amount',
            'or_number',
            'distance',
            'feeder',
            'year',
            'area',
            'municipality',
            'barangay',
            'membership'
        )

dashboard/modules/views/dashboard_add.py
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.shortcuts import render
from django.views import View

from accounts.constants import ADMIN
from accounts.models import Account


def correct_user_check(user):
    return user.user_type == ADMIN

class DashboardAddView(LoginRequiredMixin, UserPassesTestMixin, View):
    def get(self, request):

        context = {
            'page_title': 'Dashboard Add',
            'location': 'add',
        }

        return render(request, 'dashboard/add.html', context)

    def test_func(self):
        return correct_user_check(self.request.user)

dashboard/modules/views/dashboard_home.py
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.shortcuts import render
from django.views import View

from accounts.constants import ADMIN
from accounts.models import Account


def correct_user_check(user):
    return user.user_type == ADMIN

class DashboardHomeView(LoginRequiredMixin, UserPassesTestMixin, View):
    def get(self, request):

        context = {
            'page_title': 'Dashboard Home',
            'location': 'home',
        }

        return render(request, 'dashboard/home.html', context)

    def test_func(self):
        return correct_user_check(self.request.user)

dashboard/modules/views/dashboard_users.py
from django.contrib.auth.mixins import UserPassesTestMixin, LoginRequiredMixin
from django.shortcuts import render
from django.views import View

from accounts.constants import ADMIN
from accounts.models import Account


def correct_user_check(user):
    return user.user_type == ADMIN


class DashboardUserView(LoginRequiredMixin, UserPassesTestMixin, View):
    def get(self, request, *args, **kwargs):
        accounts = Account.objects.all()

        context = {
            'page_title': 'Dashboard: Users',
            'location': 'users',
            'accounts': accounts,
        }

        return render(request, 'dashboard/users/home.html', context)

    def test_func(self):
        return correct_user_check(self.request.user)

dashboard/views.py
from django.shortcuts import render

# Create your views here.

turn_on/modules/views/membership_view.py
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.http import HttpResponseRedirect
from django.shortcuts import render, get_object_or_404

# Create your views here.
from django.urls import reverse
from django.views import View

from accounts.constants import ADMIN
from turn_on.forms import MembershipForm
from turn_on.models import Membership


def correct_user_check(user):
    return user.user_type == ADMIN


class MembershipListView(LoginRequiredMixin, UserPassesTestMixin, View):
    def get(self, request):
        memberships = Membership.objects.all()

        context = {
            'page_title': 'Membership List',
            'location': 'membership',
            'memberships': memberships
        }

        return render(request, 'dashboard/membership/list.html', context)

    def test_func(self):
        return correct_user_check(self.request.user)


class MembershipCreateView(LoginRequiredMixin, UserPassesTestMixin, View):
    def get(self, request, *args, **kwargs):
        form = MembershipForm()

        context = {
            'page_title': 'Add Membership',
            'location': 'membership',
            'form': form,
        }

        return render(request, 'dashboard/membership/form.html', context)

    def post(self, request, *args, **kwargs):
        form = MembershipForm(data=request.POST)

        if form.is_valid():
            membership = form.save(commit=False)
            membership.created_by = request.user
            membership.save()

            messages.success(request, 'Membership created!', extra_tags='success')
            return HttpResponseRedirect(reverse('membership_list'))

        else:
            context = {
                'page_title': 'Add Membership',
                'location': 'membership',
                'form': form,
            }

            messages.error(request, form.errors, extra_tags='danger')
            return render(request, 'dashboard/membership/form.html', context)

    def test_func(self):
        return correct_user_check(self.request.user)


class MembershipUpdateView(LoginRequiredMixin, UserPassesTestMixin, View):
    def get(self, request, *args, **kwargs):
        obj = get_object_or_404(Membership, pk=kwargs.get('pk', None))
        form = MembershipForm(instance=obj)

        context = {
            'page_title': f'Update {obj}',
            'location': 'membership',
            'form': form,
            'obj': obj
        }

        return render(request, 'dashboard/membership/form.html', context)

    def post(self, request, *args, **kwargs):
        obj = get_object_or_404(Membership, pk=kwargs.get('pk', None))
        form = MembershipForm(instance=obj, data=request.POST)

        if form.is_valid():
            membership = form.save(commit=False)
            membership.last_updated_by = request.user
            membership.save()

            messages.success(request, f'{obj} updated!', extra_tags='success')
            return HttpResponseRedirect(reverse('membership_detail', kwargs={'pk': obj.pk}))

        else:
            context = {
                'page_title': f'Update {obj}',
                'location': 'membership',
                'form': form,
                'obj': obj
            }
            messages.error(request, form.errors, extra_tags='danger')
            return render(request, 'dashboard/membership/form.html', context)

    def test_func(self):
        return correct_user_check(self.request.user)


class MembershipDeleteView(LoginRequiredMixin, UserPassesTestMixin, View):
    def get(self, request, *args, **kwargs):
        obj = get_object_or_404(Membership, pk=kwargs.get('pk', None))

        context = {
            'page_title': f'Delete {obj}',
            'location': 'membership',
            'obj': obj,
        }

        return render(request, 'dashboard/membership/delete.html', context)

    def post(self, request, *args, **kwargs):
        obj = get_object_or_404(Membership, pk=kwargs.get('pk', None))

        obj.delete()
        return HttpResponseRedirect(reverse('membership_list'))

    def test_func(self):
        return correct_user_check(self.request.user)


class MembershipDetailView(LoginRequiredMixin, UserPassesTestMixin, View):
    def get(self, request, *args, **kwargs):
        obj = get_object_or_404(Membership, pk=kwargs.get('pk', None))

        context = {
            'page_title': f'Membership Detail: {obj}',
            'location': 'membership',
            'obj': obj
        }

        return render(request, 'dashboard/membership/detail.html', context)

    def test_func(self):
        return correct_user_check(self.request.user)

turn_on/views.py
from django.shortcuts import render

# Create your views here.

templates/dashboard/turn_on/delete.html
{% extends 'dashboard/base.html' %}
{% load static %}
{% load humanize %}

{% block head_css %}
{% endblock %}

{% block head_js %}
{% endblock %}

{% block content %}
    <div class="container">
        <nav aria-label="breadcrumb">
            <ol class="breadcrumb">
                <li class="breadcrumb-item" aria-current="page">
                    <a href="{% url 'dashboard_home_view' %}">Home</a>
                </li>
                <li class="breadcrumb-item">
                    <a href="{% url 'turn_on_list' %}">Turn On List</a>
                </li>
                <li class="breadcrumb-item active">
                    {{ page_title }}
                </li>
            </ol>
        </nav>
    </div>
    <div class="container">
        <div class="card">
        <div class="card-header">
            <h5 class="card-title">{{ page_title }}</h5>
        </div>
        <div class="card-body">
            <div class="alert alert-danger">
                This is a destructive operation and cannot be undone. Are you sure you want to delete {{ obj }}
            </div>
            <form method="post">
                {% csrf_token %}
                <div class="form-group">
                    <button type="submit" class="btn btn-danger">Yes I am</button>
                </div>
            </form>
        </div>
    </div>
    </div>
{% endblock %}

{% block scripts %}
{% endblock %}

templates/dashboard/turn_on/detail.html
{% extends 'dashboard/base.html' %}
{% load static %}
{% load humanize %}

{% block head_css %}
{% endblock %}

{% block head_js %}
{% endblock %}

{% block content %}
    <div class="container">
        <nav aria-label="breadcrumb">
            <ol class="breadcrumb">
                <li class="breadcrumb-item" aria-current="page">
                    <a href="{% url 'dashboard_home_view' %}">Home</a>
                </li>
                <li class="breadcrumb-item">
                    <a href="{% url 'turn_on_list' %}">Turn On List</a>
                </li>
                <li class="breadcrumb-item active">
                    {{ page_title }}
                </li>
            </ol>
        </nav>
    </div>
    <div class="container">
        <div class="card">
            <div class="card-header d-flex justify-content-between align-items-baseline">
                <div class="card-title">{{ page_title }}</div>
                <div>
                    <a class="btn btn-warning text-white" href="{% url 'turn_on_update' obj.pk %}">UPDATE</a>
                    <a class="btn btn-danger text-white" href="{% url 'turn_on_delete' obj.pk %}">DELETE</a>
                </div>

            </div>
            <div class="card-body">
                <div class="card-columns">
                    <div class="card">
                        <div class="card-header">Applicant</div>
                        <div class="card-body">
                            <div class="card-text">Application number: <strong>{{ obj.number }}</strong></div>
                            <div class="card-text">Name: <strong>{{ obj.get_full_name }}</strong></div>
                            <div class="card-text">Membership type: <strong>{{ obj.membership }}</strong></div>
                            <div class="card-text">Spouse: <strong>{{ obj.spouse }}</strong></div>
                        </div>
                    </div>
                    <div class="card">
                        <div class="card-header">Connection Detail</div>
                        <div class="card-body">
                            <div class="card-text">Installation type: <strong>{{ obj.install }}</strong></div>
                            <div class="card-text">Connection type: <strong>{{ obj.connection }}</strong></div>
                            <div class="card-text">Cons: <strong>{{ obj.cons }}</strong></div>
                            <div class="card-text">Amount: <strong>{{ obj.amount }}</strong></div>
                        </div>
                    </div>
                    <div class="card">
                        <div class="card-header">Status</div>
                        <div class="card-body">
                            <div class="card-text">Status:
                                {% if obj.is_approved %}
                                    <strong class="text-success">APPROVED</strong>
                                {% else %}
                                    <strong class="text-warning">PENDING</strong>
                                {% endif %}
                            </div>
                            <div class="card-text">Year applied: <strong>{{ obj.year }}</strong></div>
                            <div class="card-text">Date created: <strong>{{ obj.created|date }}</strong></div>
                            <div class="card-text">Date last updated: <strong>{{ obj.updated|date }}</strong></div>
                        </div>
                    </div>
                </div>
                <div class="card">
                    <div class="card-header">
                        Address ({{ obj.area }})
                    </div>
                    <div class="card-body">
                        <div class="row">
                            <div class="col-md-8">
                                <div class="card-text">Address: <strong>{{ obj.address }}</strong></div>
                                <div class="card-text">Municipality: <strong>{{ obj.municipality }}</strong></div>
                                <div class="card-text">Barangay: <strong>{{ obj.barangay }}</strong></div>
                            </div>
                            <div class="col-md-4">
                                <div class="card-text">Distance: <strong>{{ obj.distance }}</strong></div>
                                <div class="card-text">Feeder: <strong>{{ obj.feeder }}</strong></div>
                            </div>
                        </div>
                    </div>
                    <div class="card-footer">
                        <div class="card-text">Encoded by: <strong>{{ obj.base_profile.full_name }}</strong></div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    </div>
{% endblock %}

{% block scripts %}
{% endblock %}

templates/dashboard/turn_on/form.html
{% extends 'dashboard/base.html' %}
{% load static %}
{% load humanize %}
{% load crispy_forms_tags %}

{% block head_css %}
{% endblock %}

{% block head_js %}
{% endblock %}

{% block content %}
    <div class="container">
        <nav aria-label="breadcrumb">
            <ol class="breadcrumb">
                <li class="breadcrumb-item" aria-current="page">
                    <a href="{% url 'dashboard_home_view' %}">Home</a>
                </li>
                <li class="breadcrumb-item active">
                    <a href="{% url 'turn_on_list' %}">Turn On List</a>
                </li>
                <li class="breadcrumb-item active">
                    {{ page_title }}
                </li>
            </ol>
        </nav>
    </div>
    <div class="container">
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}

            {{ form|crispy }}

            <div class="form-group">
                <button type="submit" class="btn btn-primary">SUBMIT</button>
            </div>
        </form>
    </div>
{% endblock %}

{% block scripts %}
    <script type="text/javascript">
        $(window).on('load', function (e) {
            var province_id = 22;
            var province_url = "{% url 'cities_by_province' %}?id=" + province_id;

            $.get(province_url, function (data, status) {
                var opts = '';

                $.each(data, function (i, item) {
                    opts = opts + "<option value='" + item.pk + "'>" + item.name + "</option>";
                });

                $('#id_area').empty().append(opts);
                $('#id_municipality').empty().append(opts);
            });
        });
    </script>
{% endblock %}

templates/dashboard/turn_on/list.html
{% extends 'dashboard/base.html' %}
{% load static %}
{% load humanize %}

{% block head_css %}
{% endblock %}

{% block head_js %}
{% endblock %}

{% block content %}
    <div class="container">
        <nav aria-label="breadcrumb">
            <ol class="breadcrumb">
                <li class="breadcrumb-item" aria-current="page">
                    <a href="{% url 'dashboard_home_view' %}">Home</a>
                </li>
                <li class="breadcrumb-item active">
                    {{ page_title }}
                </li>
            </ol>
        </nav>
    </div>
    <div class="card">
        <div class="card-header d-flex justify-content-between align-items-baseline">
            <div class="card-title">Turn On List</div>
            <a class="btn btn-primary" href="{% url 'turn_on_create' %}">CREATE</a>
        </div>
        <div class="card-body">
            <table class="table table-hover small">
                <thead>
                    <tr>
                        <th>Name</th>
                        <th>Membership</th>
                        <th>Area</th>
                        <th>Created By</th>
                    </tr>
                </thead>
                <tbody>
                    {% for obj in turn_on %}
                        <tr>
                            <td><a class="text-primary" href="{% url 'turn_on_detail' obj.pk %}">{{ obj.get_full_name }}</a></td>
                            <td>{{ obj.membership }}</td>
                            <td>{{ obj.area }}</td>
                            <td>{{ obj.created_by }}</td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
{% endblock %}

{% block scripts %}
{% endblock %}